DROP TABLE POST IF EXISTS;
DROP TABLE CHAT IF EXISTS;
DROP TABLE TOUCHUSER IF EXISTS;
-- DROP TABLE USER IF EXISTS;

CREATE TABLE TOUCHUSER (
	id INTEGER IDENTITY,
	name VARCHAR(20) not null,
	pw VARCHAR(20) not null
);
ALTER TABLE TOUCHUSER ADD CONSTRAINT username_uniqe UNIQUE (name);

CREATE TABLE CHAT (
	id INTEGER IDENTITY,
	last_modified TIMESTAMP default CURRENT_TIMESTAMP,
	chat_name VARCHAR(20),
	owner_id INTEGER,
	owner_name VARCHAR(255),
	party_name VARCHAR(255)
);
ALTER TABLE CHAT ADD CONSTRAINT user_fk FOREIGN KEY( owner_id ) REFERENCES TOUCHUSER ( id );
ALTER TABLE CHAT ADD CONSTRAINT chat_uniqe UNIQUE (chat_name, owner_id);

CREATE TABLE POST (
	id INTEGER IDENTITY,
	created TIMESTAMP default CURRENT_TIMESTAMP,
	chat_id INTEGER,
	direction TINYINT,
	post_text VARCHAR(1000)
);
ALTER TABLE POST ADD CONSTRAINT chat_fk FOREIGN KEY( chat_id ) REFERENCES CHAT( id ); 

insert into TOUCHUSER  (name, pw) values ('admin', 'admin');
